openapi: 3.0.0
info:
  title: Auth API Node.js
  version: 1.0.0
  description: API de autenticación con validación, JWT y control de roles

servers:
  - url: http://localhost:3000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
paths:
  /auth/register:
    post:
      summary: Registro de nuevo usuario
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, last_name, email, password, phone_number, gender]
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone_number:
                  type: string
                gender:
                  type: string
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: Datos inválidos
        '409':
          description: Usuario ya existe

  /auth/login:
    post:
      summary: Iniciar sesión y obtener token JWT
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Inicio de sesión exitoso
        '401':
          description: Credenciales inválidas

  /profile:
    get:
      summary: Obtener perfil del usuario autenticado
      tags:
        - Usuario
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfil del usuario autenticado
        '401':
          description: Token inválido o expirado
        '403':
          description: Token no proporcionado

  /admin/users:
    get:
      summary: Obtener listado de usuarios (admin only)
      tags:
        - Admin
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de usuarios
        '401':
          description: Token inválido o expirado
        '403':
          description: Acceso denegado (requiere rol admin)