openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API Node.js de autenticaci칩n con JWT y PostgreSQL

servers:
  - url: http://localhost:3000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
paths:
  /auth/register:
    post:
      summary: Registrar nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, last_name, email, password]
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: Error en la solicitud
        '409':
          description: Usuario ya existe

  /auth/login:
    post:
      summary: Iniciar sesi칩n
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso, retorna token
        '401':
          description: Credenciales inv치lidas

  /profile:
    get:
      summary: Obtener perfil del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfil del usuario
        '401':
          description: Token inv치lido o expirado
        '403':
          description: Token no proporcionado